opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - sorted_imports

identifier_name:
  excluded:
    - uk

line_length:
  ignores_urls: true
  ignores_comments: true
